Feature/community store
ample/crds-net pull request #1
Opened 2019-04-18 14:36 UTC by J-Byron

## Problem
*Document current behavior and why it's undesirable here.*

## Solution
*Document how the behavior was fixed or enhanced here.*

### Corresponding Branch
*Add link to crdschurch/repo-name-here#issue-number (if applicable). This helps the code reviewer know that corresponding work exists and where to find it.*

## Testing
*Include information on how to test your work here (if applicable).*

2019-04-18 21:32 UTC, tcmacdonald commented on _assets/stylesheets/pages/_community-store.scss
> +    width: 100%;
Please correct the indentions to 2 spaces, per tab.

2019-04-18 21:33 UTC, tcmacdonald commented on community-store.html
> +<div class="row" style="max-width:100%; margin-left: 0;">
Can you please move all inline styles into your stylesheet?

2019-04-18 21:34 UTC, tcmacdonald commented on community-store.html
> +  style="background-image: url('https://crds-cms-uploads.imgix.net/content/images/streaming-anywhere-hero-off.jpg?auto=format,compress&w=597&fit=crop');">
Did you intend to crop this image to `597px` wide?

2019-04-18 21:34 UTC, tcmacdonald commented on community-store.html
> +    <div class="card-deck carousel" data-crds-carousel="mobile-scroll" style="left: 30px;">
More inline styles here.

2019-04-18 21:35 UTC, tcmacdonald commented on community-store.html
> +                ix-src="//crds-cms-uploads.imgix.net/content/images/crossroads-go-header-imgs-nicaragua.jpg?w=108&h=108&fit=crop&format=auto,compress">
Can you make sure that all `<img />` elements have `alt="..."` attributes?

2019-04-18 21:37 UTC, tcmacdonald commented on _assets/stylesheets/pages/_community-store.scss
> +    height: 597px;
Can we make this a `min-height` declaration?

2019-04-18 21:38 UTC, tcmacdonald commented on _assets/stylesheets/pages/_community-store.scss
> +    @media (min-width: 993px){
Please use the variables provided by Bootstrap for the calculation stuff. `$screen-md` for example is `992px` so you could probably do this... 

```
@media (min-width: $screen-md + 1){ ... }
```

2019-04-18 21:40 UTC, tcmacdonald commented on _assets/stylesheets/pages/_community-store.scss
> +            font-family: "lexia";
Please use `$accent-font-face` for this font-family declaration. 

https://github.com/crdschurch/crds-styles/blob/development/assets/stylesheets/_variables.scss#L5

2019-04-18 21:41 UTC, tcmacdonald commented on community-store.html
> +        </div> -->
Please remove any commented out code.

2019-04-18 21:43 UTC, tcmacdonald requested changes
Looks good @J-Byron. I left some comments above ☝️. Please take a look and let me know if you have any questions. 

Thanks, Taylor

2019-04-19 13:45 UTC, tcmacdonald commented on community-store.html
> +        <h1 class="title text-uppercase">Get Involved</h1>
Can you reduce the weight on this element to `500`?

2019-04-19 13:46 UTC, tcmacdonald commented on community-store.html
> +  <h1 class="font-family-condensed-extra text-uppercase font-size-h1 flush-top">you were born for adventure</h1>
Can you convert this element to an `<h2>`? There should only be one `<h1>` element per page.

2019-04-19 13:46 UTC, tcmacdonald commented on community-store.html
> +  <h1 class="font-family-condensed-extra text-uppercase font-size-h1">Find people near you</h1>
Same as above, please make this an `<h2>`.

2019-04-19 14:02 UTC, tcmacdonald requested changes
Thanks @J-Byron – almost there!

I added a couple more inline comments ☝️ 

And lastly, we need to add some default background colors for any element that has a background image. Since those images are big, they may take a while to load and until they do, the white text isn't readable against a white background. Take a look at the following screenshot for some suggestions but use your best judgement if you think a different color works better... 

![Community_Store___Crossroads](https://user-images.githubusercontent.com/50378/56427511-265abb00-628a-11e9-9cc8-5ea14d788672.png)

Let me know if you have any other questions. Thanks!

2019-04-19 15:39 UTC, seancdavis commented
Closing this one to see if it resolves the duplicate commit issues here. I'll reopen if it does not.

2019-04-19 15:39 UTC, closed without merging